import type { ModelTier, WorkerType } from './db.js';

export interface Classification {
  isLong: boolean;
  workerType: WorkerType;
  modelTier: ModelTier;
  /** When set, multiple workers should handle this task (Phase D). */
  multiWorker?: WorkerType[];
}

/**
 * Quick-path patterns: messages that should be handled inline (< 30s).
 * These are checked first. If any match, the message is classified as quick.
 */
const QUICK_PATTERNS: RegExp[] = [
  // Bot commands and special commands
  /^\/\w+/,
  /^convolife$/i,
  /^checkpoint$/i,

  // Status checks and simple lookups
  /^what('?s| is) (the )?(status|time|date|weather)/i,
  /^(hi|hey|hello|yo|sup|thanks|thank you|ok|okay|got it|cool|nice|good)\s*[.!?]?$/i,

  // Short questions (under 60 chars, no action verbs)
  /^(who|what|where|when|why|how|is|are|do|does|did|can|could|will|would|should)\b.{0,55}\?$/i,

  // Memory recall
  /^(remember|recall|what did (i|we)|last time)/i,

  // Simple lookups
  /^(show|list|get) (my )?(tasks|schedule|memories|sessions)/i,

  // Media messages (generated by media.ts buildPhotoMessage/buildDocumentMessage/buildVideoMessage).
  // These always contain "analyze" in the boilerplate which would trigger Soundwave dispatch.
  // Must stay inline so Claude can read the local file.
  /^(Photo|Document|Video) received/i,

  // Conversational / meta
  /^(convolife|checkpoint|status|ping)\b/i,
];

/**
 * Worker routing rules. Order matters: first match wins.
 * Each entry maps keyword patterns to a worker type.
 */
const WORKER_ROUTES: Array<{ patterns: RegExp[]; worker: WorkerType }> = [
  // Starscream: social media, LinkedIn, content scheduling
  {
    worker: 'starscream',
    patterns: [
      /\blinkedin\b/i,
      /\b(social media|social post)\b/i,
      /\bschedule\s+(a\s+)?post\b/i,
      /\b(write|draft|create)\s+(a\s+)?(post|tweet|thread|article)\b/i,
      /\bstarscream\b/i,
      /\bcontent\s+(calendar|strategy|plan)\b/i,
    ],
  },

  // Ravage: coding, GitHub, builds, deploys
  {
    worker: 'ravage',
    patterns: [
      /\b(build|code|implement|refactor|fix|debug|patch)\b/i,
      /\b(commit|push|merge|rebase|cherry.?pick)\b/i,
      /\bgithub\b/i,
      /\b(pull request|PR|pr)\b/i,
      /\bdeploy\b/i,
      /\b(write|add|create|update)\s+(a\s+)?(function|class|module|component|test|feature|endpoint|api|script)\b/i,
      /\bravage\b/i,
      /\b(npm|pip|cargo|docker)\b/i,
      /\b(migrate|migration|schema)\b/i,
    ],
  },

  // Soundwave: research, analysis, reports, pipeline work
  {
    worker: 'soundwave',
    patterns: [
      /\b(research|investigate|analyze|analyse)\b/i,
      /\breview\s+(the\s+)?pipeline\b/i,
      /\bmorning\s+report\b/i,
      /\b(market|competitor|industry)\s+(research|analysis|report)\b/i,
      /\bsoundwave\b/i,
      /\b(deep\s+dive|comprehensive|thorough)\s+(review|analysis|report)\b/i,
      /\bwrite\s+(a\s+)?(report|analysis|brief|summary|review)\b/i,
    ],
  },

  // AstroTrain: DSP/SCM simulation, supply chain, logistics, procurement
  {
    worker: 'astrotrain',
    patterns: [
      /\bastrotrain\b/i,
      /\b(supply\s*chain|scm)\b/i,
      /\b(dsp|demand\s+signal)\b/i,
      /\b(procurement|sourcing|vendor)\s+(simulation|optimization|analysis)\b/i,
      /\b(logistics|warehouse|inventory)\s+(simulation|optimization|model)\b/i,
      /\b(simulation|simulate)\s+(a\s+)?(supply|demand|procurement|logistics|scm)\b/i,
      /\b(episodic|episode)\s+(simulation|game|scenario)\b/i,
    ],
  },
];

/** All named worker types (excludes 'default'). Used for bracket exclusion. */
const NAMED_WORKERS: WorkerType[] = WORKER_ROUTES.map((r) => r.worker);

/** Non-ravage worker names. Used for code context override detection. */
const NON_RAVAGE_WORKERS: WorkerType[] = NAMED_WORKERS.filter((w) => w !== 'ravage');

/**
 * Code artifact patterns: when these appear alongside a non-ravage worker
 * name, the message is about coding work ON that worker's code, not a task
 * FOR that worker. Force route to ravage.
 *
 * Example: "fix the Starscream classifier.ts" -> ravage (not starscream)
 * Example: "update Soundwave's CLAUDE.md" -> ravage (not soundwave)
 * Counter: "Starscream, write a LinkedIn post" -> starscream (no code artifacts)
 */
const CODE_ARTIFACT_PATTERNS: RegExp[] = [
  // File extensions (explicit list to avoid matching URLs like example.com)
  /\.\b(ts|js|py|md|json|html|css|sql|sh|yaml|yml|toml|cfg|cjs|mjs)\b/i,
  // Path segments
  /\b(src|dist|scripts|workers|store|dashboard|tests?)\//i,
  // Config/project files
  /\bCLAUDE\.md\b/,
  /\b(package\.json|tsconfig|pyproject|ecosystem\.config)\b/i,
  // Code structure terms (only when specific enough to not false-positive)
  /\b(source\s*code|codebase|repo(sitory)?|workflow|pipeline\s+code)\b/i,
  /\b(classifier|dispatcher|scheduler|worker\.ts|result.?poller)\b/i,
];

/**
 * Long-task indicators: if a message matches any of these and didn't
 * match a quick pattern, it gets dispatched to a worker.
 */
const LONG_INDICATORS: RegExp[] = [
  // Explicit action verbs that imply multi-step work
  /\b(build|create|implement|write|develop|design|architect|scaffold)\b/i,
  /\b(review|audit|analyze|research|investigate)\b/i,
  /\b(refactor|rewrite|migrate|upgrade|overhaul)\b/i,
  /\b(deploy|release|ship|publish)\b/i,
  /\b(fix|debug|troubleshoot|diagnose)\b/i,

  // Slide deck / presentation
  /\b(slide\s*deck|presentation|pitch\s*deck)\b/i,

  // Multi-file / project-scope work
  /\bacross\s+(all|the|every)\b/i,
  /\b(entire|whole)\s+(project|codebase|repo)\b/i,

  // Explicit dispatch requests
  /\bdispatch\b/i,
];

/**
 * Opus-tier indicators: tasks requiring the most capable model.
 * Architecture decisions, security audits, complex multi-step reasoning.
 */
const OPUS_INDICATORS: RegExp[] = [
  /\b(architect|architecture|system\s+design)\b/i,
  /\b(security|vulnerability|audit|penetration)\b/i,
  /\b(comprehensive|thorough|deep)\s+(review|audit|analysis|refactor)\b/i,
  /\b(redesign|overhaul|rewrite)\b/i,
  /\b(strategic|strategy)\s+(plan|review|analysis)\b/i,
  /\buse\s+opus\b/i, // Explicit model request
];

/**
 * Haiku-tier indicators: simple tasks that don't need full sonnet.
 * Formatting, simple lookups, boilerplate generation.
 */
const HAIKU_INDICATORS: RegExp[] = [
  /\b(format|reformat|prettify|lint)\b/i,
  /\b(rename|move|copy)\s+(the\s+)?(file|variable|function|class)\b/i,
  /\b(list|show|get)\s+(all\s+)?(files|imports|exports|dependencies)\b/i,
  /\bboilerplate\b/i,
  /\buse\s+haiku\b/i, // Explicit model request
];

/**
 * Determine the model tier for a task based on complexity indicators.
 * Opus for architecture/security/complex work, haiku for simple tasks,
 * sonnet for everything else.
 */
function determineModelTier(text: string): ModelTier {
  // Explicit model requests take priority
  if (/\buse\s+opus\b/i.test(text)) return 'opus';
  if (/\buse\s+haiku\b/i.test(text)) return 'haiku';

  // Check opus indicators first (complex tasks)
  if (OPUS_INDICATORS.some((p) => p.test(text))) return 'opus';

  // Check haiku indicators (simple tasks)
  if (HAIKU_INDICATORS.some((p) => p.test(text))) return 'haiku';

  // Default: sonnet
  return 'sonnet';
}

/**
 * Get all worker types that match a message.
 * Used for multi-topic detection and multi-agent composition.
 */
function getMatchedWorkers(text: string): WorkerType[] {
  const matched: WorkerType[] = [];
  for (const route of WORKER_ROUTES) {
    const hit = route.patterns.some((p) => p.test(text));
    if (hit) matched.push(route.worker);
  }
  return matched;
}

/**
 * Count how many different worker routes a message matches.
 */
function countWorkerMatches(text: string): number {
  return getMatchedWorkers(text).length;
}

/**
 * Classify an incoming message as quick (inline) or long (dispatch to worker).
 *
 * Classification flow:
 * 1. If the message matches a quick pattern, return quick (inline).
 * 2. If the message is multi-topic (matches 2+ worker routes), keep inline.
 *    Dispatching a multi-topic message to one worker drops the other topics.
 * 3. If the message is long (200+ chars) with multiple sentences and only
 *    incidentally matches a long indicator, keep inline. These are discussions,
 *    not build orders.
 * 4. If the message matches a long indicator, route to the appropriate worker.
 * 5. If no pattern matches, default to quick (inline).
 */
export function classifyMessage(text: string): Classification {
  const trimmed = text.trim();

  // Strip @prefix for classification (routing already handled by router.ts)
  const stripped = trimmed.replace(/^@\w+\s+/, '');

  // Strip backtick-wrapped and bracket-wrapped text before classification.
  // Both denote references to agents/concepts, not commands to them.
  // e.g. "Rename the `Starscream` card" won't route to Starscream.
  // e.g. "[Starscream] posted twice" won't route to Starscream.
  const cleaned = stripped.replace(/`[^`]+`/g, '').replace(/\[[^\]]+\]/g, '');

  // Bracket exclusion: if an agent name appears ONLY inside [brackets]
  // (not bare in the message), exclude that worker from dispatch entirely.
  // Brackets signal a reference, not a command. Applies to all workers.
  const bracketContents = stripped.match(/\[[^\]]+\]/g) || [];
  const bracketExcluded = new Set<WorkerType>();
  for (const name of NAMED_WORKERS) {
    const inBrackets = bracketContents.some((b) =>
      new RegExp(`\\b${name}\\b`, 'i').test(b),
    );
    const outsideBrackets = new RegExp(`\\b${name}\\b`, 'i').test(cleaned);
    if (inBrackets && !outsideBrackets) {
      bracketExcluded.add(name);
    }
  }

  // Code context override: if a message mentions code artifacts (file
  // extensions, paths, config files) alongside a non-ravage worker name,
  // the user is talking about coding work ON that worker, not dispatching
  // TO it. Force those workers out of routing so ravage picks up the task.
  //
  // Suppressed for questions (starts with question word or ends with ?)
  // because "Why did Starscream post twice...check the classifier" is a
  // question about behavior, not a code change request.
  const hasCodeArtifacts = CODE_ARTIFACT_PATTERNS.some((p) => p.test(stripped));
  const isQuestionForm =
    /^(who|what|where|when|why|how|is|are|do|does|did|can|could|will|would|should)\b/i.test(stripped) ||
    /\?\s*$/.test(stripped);
  const codeContextWorkers = new Set<WorkerType>();
  if (hasCodeArtifacts && !isQuestionForm) {
    for (const name of NON_RAVAGE_WORKERS) {
      if (new RegExp(`\\b${name}\\b`, 'i').test(cleaned)) {
        codeContextWorkers.add(name);
      }
    }
  }

  // 1. Check quick patterns first (use stripped, not cleaned -- quick
  //    patterns match message structure like /commands and greetings)
  for (const pattern of QUICK_PATTERNS) {
    if (pattern.test(stripped)) {
      return { isLong: false, workerType: 'default', modelTier: 'sonnet' };
    }
  }

  // 2. Multi-topic detection: if the message touches 2+ worker domains
  // AND has long task indicators, dispatch to all matched workers (Phase D).
  // If it doesn't have long indicators, keep inline (it's a discussion).
  // Use `cleaned` so backtick-wrapped agent names don't trigger routing.
  const matchedWorkers = getMatchedWorkers(cleaned).filter(
    (w) => !bracketExcluded.has(w) && !codeContextWorkers.has(w),
  );
  if (matchedWorkers.length >= 2) {
    const hasLongIndicators = LONG_INDICATORS.some((p) => p.test(cleaned));
    if (hasLongIndicators) {
      // Guard: conversational messages (150+ chars, 3+ sentences) that are
      // questions or meta-discussions should stay inline even if multi-topic.
      // Lower threshold than step 3 (200) because multi-topic matches are more
      // prone to false positives from discussions mentioning multiple domains.
      const sentCount = (stripped.match(/[.!?]\s/g) || []).length + 1;
      if (stripped.length > 150 && sentCount >= 3) {
        const isQuestion = /\?\s*$/.test(stripped);
        const startsWithQ = /^(who|what|where|when|why|how|is|are|do|does|did|can|could|will|would|should)\b/i.test(stripped);
        const isMeta = /\b(supposed to|intention|do not make changes|don't make changes|this is a discussion|still experiencing|still dealing|still getting|was the plan|want to know)\b/i.test(stripped);

        if (isQuestion || startsWithQ || isMeta) {
          return { isLong: false, workerType: 'default', modelTier: 'sonnet' };
        }
      }

      const modelTier = determineModelTier(cleaned);
      return {
        isLong: true,
        workerType: matchedWorkers[0], // Primary worker (first match)
        modelTier,
        multiWorker: matchedWorkers,
      };
    }
    // No long indicators with multi-topic = discussion, keep inline
    return { isLong: false, workerType: 'default', modelTier: 'sonnet' };
  }

  // 3. Long conversational messages guard: messages over 200 chars with 3+
  // sentences are likely discussions that incidentally contain action verbs.
  // Only dispatch short, focused instructions.
  const sentenceCount = (stripped.match(/[.!?]\s/g) || []).length + 1;
  if (stripped.length > 200 && sentenceCount >= 3) {
    // Exception: if the message explicitly names a worker AND is imperative
    // (not a question or meta-discussion about the worker), dispatch anyway.
    // Use `cleaned` so backtick-wrapped names don't count as explicit.
    // Code-context workers don't count as explicit dispatch targets either.
    const explicitWorkerMatch = cleaned.match(/\b(starscream|ravage|soundwave|astrotrain)\b/i);
    const explicitWorker = explicitWorkerMatch
      ? !codeContextWorkers.has(explicitWorkerMatch[1].toLowerCase() as WorkerType)
      : false;
    if (!explicitWorker) {
      return { isLong: false, workerType: 'default', modelTier: 'sonnet' };
    }

    // Even with explicit worker name, keep inline if it's a discussion:
    // - Ends with ? (question about the worker, not a command to it)
    // - Starts with question words (who/what/where/when/why/how/is/are/do/does/did/can/could/will/would/should)
    // - Contains meta-discussion phrases ("supposed to", "intention", "do not make changes")
    const isQuestion = /\?\s*$/.test(stripped);
    const startsWithQuestionWord = /^(who|what|where|when|why|how|is|are|do|does|did|can|could|will|would|should)\b/i.test(stripped);
    const isMetaDiscussion = /\b(supposed to|intention|do not make changes|don't make changes|this is a discussion|still experiencing|still dealing|still getting|was the plan|want to know)\b/i.test(stripped);

    if (isQuestion || startsWithQuestionWord || isMetaDiscussion) {
      return { isLong: false, workerType: 'default', modelTier: 'sonnet' };
    }
  }

  // 4. Check if this looks like a long task (use cleaned)
  const isLong = LONG_INDICATORS.some((p) => p.test(cleaned));

  if (!isLong) {
    // Short message with no long indicators: handle inline
    return { isLong: false, workerType: 'default', modelTier: 'sonnet' };
  }

  // Determine model tier based on task complexity
  const modelTier = determineModelTier(cleaned);

  // 5. Route to the appropriate worker (use cleaned, skip bracket-excluded
  //    and code-context-overridden workers)
  for (const route of WORKER_ROUTES) {
    if (bracketExcluded.has(route.worker)) continue;
    if (codeContextWorkers.has(route.worker)) continue;
    for (const pattern of route.patterns) {
      if (pattern.test(cleaned)) {
        return { isLong: true, workerType: route.worker, modelTier };
      }
    }
  }

  // 6. Code context fallback: if no worker matched because codeContextWorkers
  //    excluded the only matching worker, route to ravage. The user is doing
  //    coding work ON a worker (e.g. "rewrite Soundwave CLAUDE.md").
  if (codeContextWorkers.size > 0) {
    return { isLong: true, workerType: 'ravage', modelTier };
  }

  // Long task but no specific worker match: use default
  return { isLong: true, workerType: 'default', modelTier };
}
