import type { WorkerType } from './db.js';

export interface Classification {
  isLong: boolean;
  workerType: WorkerType;
}

/**
 * Quick-path patterns: messages that should be handled inline (< 30s).
 * These are checked first. If any match, the message is classified as quick.
 */
const QUICK_PATTERNS: RegExp[] = [
  // Bot commands and special commands
  /^\/\w+/,
  /^convolife$/i,
  /^checkpoint$/i,

  // Status checks and simple lookups
  /^what('?s| is) (the )?(status|time|date|weather)/i,
  /^(hi|hey|hello|yo|sup|thanks|thank you|ok|okay|got it|cool|nice|good)\s*[.!?]?$/i,

  // Short questions (under 60 chars, no action verbs)
  /^(who|what|where|when|why|how|is|are|do|does|did|can|could|will|would|should)\b.{0,55}\?$/i,

  // Memory recall
  /^(remember|recall|what did (i|we)|last time)/i,

  // Simple lookups
  /^(show|list|get) (my )?(tasks|schedule|memories|sessions)/i,

  // Media messages (generated by media.ts buildPhotoMessage/buildDocumentMessage/buildVideoMessage).
  // These always contain "analyze" in the boilerplate which would trigger Soundwave dispatch.
  // Must stay inline so Claude can read the local file.
  /^(Photo|Document|Video) received/i,

  // Conversational / meta
  /^(convolife|checkpoint|status|ping)\b/i,
];

/**
 * Worker routing rules. Order matters: first match wins.
 * Each entry maps keyword patterns to a worker type.
 */
const WORKER_ROUTES: Array<{ patterns: RegExp[]; worker: WorkerType }> = [
  // Starscream: social media, LinkedIn, content scheduling
  {
    worker: 'starscream',
    patterns: [
      /\blinkedin\b/i,
      /\b(social media|social post)\b/i,
      /\bschedule\s+(a\s+)?post\b/i,
      /\b(write|draft|create)\s+(a\s+)?(post|tweet|thread|article)\b/i,
      /\bstarscream\b/i,
      /\bcontent\s+(calendar|strategy|plan)\b/i,
    ],
  },

  // Ravage: coding, GitHub, builds, deploys
  {
    worker: 'ravage',
    patterns: [
      /\b(build|code|implement|refactor|fix|debug|patch)\b/i,
      /\b(commit|push|merge|rebase|cherry.?pick)\b/i,
      /\bgithub\b/i,
      /\b(pull request|PR|pr)\b/i,
      /\bdeploy\b/i,
      /\b(write|add|create|update)\s+(a\s+)?(function|class|module|component|test|feature|endpoint|api|script)\b/i,
      /\bravage\b/i,
      /\b(npm|pip|cargo|docker)\b/i,
      /\b(migrate|migration|schema)\b/i,
    ],
  },

  // Soundwave: research, analysis, reports, pipeline work
  {
    worker: 'soundwave',
    patterns: [
      /\b(research|investigate|analyze|analyse)\b/i,
      /\breview\s+(the\s+)?pipeline\b/i,
      /\bmorning\s+report\b/i,
      /\b(market|competitor|industry)\s+(research|analysis|report)\b/i,
      /\bsoundwave\b/i,
      /\b(deep\s+dive|comprehensive|thorough)\s+(review|analysis|report)\b/i,
      /\bwrite\s+(a\s+)?(report|analysis|brief|summary|review)\b/i,
    ],
  },

  // AstroTrain: DSP/SCM simulation, supply chain, logistics, procurement
  {
    worker: 'astrotrain',
    patterns: [
      /\bastrotrain\b/i,
      /\b(supply\s*chain|scm)\b/i,
      /\b(dsp|demand\s+signal)\b/i,
      /\b(procurement|sourcing|vendor)\s+(simulation|optimization|analysis)\b/i,
      /\b(logistics|warehouse|inventory)\s+(simulation|optimization|model)\b/i,
      /\b(simulation|simulate)\s+(a\s+)?(supply|demand|procurement|logistics|scm)\b/i,
      /\b(episodic|episode)\s+(simulation|game|scenario)\b/i,
    ],
  },
];

/**
 * Long-task indicators: if a message matches any of these and didn't
 * match a quick pattern, it gets dispatched to a worker.
 */
const LONG_INDICATORS: RegExp[] = [
  // Explicit action verbs that imply multi-step work
  /\b(build|create|implement|write|develop|design|architect|scaffold)\b/i,
  /\b(review|audit|analyze|research|investigate)\b/i,
  /\b(refactor|rewrite|migrate|upgrade|overhaul)\b/i,
  /\b(deploy|release|ship|publish)\b/i,
  /\b(fix|debug|troubleshoot|diagnose)\b/i,

  // Slide deck / presentation
  /\b(slide\s*deck|presentation|pitch\s*deck)\b/i,

  // Multi-file / project-scope work
  /\bacross\s+(all|the|every)\b/i,
  /\b(entire|whole)\s+(project|codebase|repo)\b/i,

  // Explicit dispatch requests
  /\bdispatch\b/i,
];

/**
 * Count how many different worker routes a message matches.
 * Multi-topic messages (matching 2+ workers) should stay inline
 * because dispatching to one worker loses context for the others.
 */
function countWorkerMatches(text: string): number {
  let matches = 0;
  for (const route of WORKER_ROUTES) {
    const hit = route.patterns.some((p) => p.test(text));
    if (hit) matches++;
  }
  return matches;
}

/**
 * Classify an incoming message as quick (inline) or long (dispatch to worker).
 *
 * Classification flow:
 * 1. If the message matches a quick pattern, return quick (inline).
 * 2. If the message is multi-topic (matches 2+ worker routes), keep inline.
 *    Dispatching a multi-topic message to one worker drops the other topics.
 * 3. If the message is long (200+ chars) with multiple sentences and only
 *    incidentally matches a long indicator, keep inline. These are discussions,
 *    not build orders.
 * 4. If the message matches a long indicator, route to the appropriate worker.
 * 5. If no pattern matches, default to quick (inline).
 */
export function classifyMessage(text: string): Classification {
  const trimmed = text.trim();

  // Strip @prefix for classification (routing already handled by router.ts)
  const stripped = trimmed.replace(/^@\w+\s+/, '');

  // 1. Check quick patterns first
  for (const pattern of QUICK_PATTERNS) {
    if (pattern.test(stripped)) {
      return { isLong: false, workerType: 'default' };
    }
  }

  // 2. Multi-topic guard: if the message touches 2+ worker domains,
  // it's a discussion, not a single task. Keep inline so Data handles all of it.
  if (countWorkerMatches(stripped) >= 2) {
    return { isLong: false, workerType: 'default' };
  }

  // 3. Long conversational messages guard: messages over 200 chars with 3+
  // sentences are likely discussions that incidentally contain action verbs.
  // Only dispatch short, focused instructions.
  const sentenceCount = (stripped.match(/[.!?]\s/g) || []).length + 1;
  if (stripped.length > 200 && sentenceCount >= 3) {
    // Exception: if the message explicitly names a worker AND is imperative
    // (not a question or meta-discussion about the worker), dispatch anyway.
    const explicitWorker = /\b(starscream|ravage|soundwave|astrotrain)\b/i.test(stripped);
    if (!explicitWorker) {
      return { isLong: false, workerType: 'default' };
    }

    // Even with explicit worker name, keep inline if it's a discussion:
    // - Ends with ? (question about the worker, not a command to it)
    // - Starts with question words (who/what/where/when/why/how/is/are/do/does/did/can/could/will/would/should)
    // - Contains meta-discussion phrases ("supposed to", "intention", "do not make changes")
    const isQuestion = /\?\s*$/.test(stripped);
    const startsWithQuestionWord = /^(who|what|where|when|why|how|is|are|do|does|did|can|could|will|would|should)\b/i.test(stripped);
    const isMetaDiscussion = /\b(supposed to|intention|do not make changes|don't make changes|this is a discussion|still experiencing|still dealing|still getting|was the plan|want to know)\b/i.test(stripped);

    if (isQuestion || startsWithQuestionWord || isMetaDiscussion) {
      return { isLong: false, workerType: 'default' };
    }
  }

  // 4. Check if this looks like a long task
  const isLong = LONG_INDICATORS.some((p) => p.test(stripped));

  if (!isLong) {
    // Short message with no long indicators: handle inline
    return { isLong: false, workerType: 'default' };
  }

  // 5. Route to the appropriate worker
  for (const route of WORKER_ROUTES) {
    for (const pattern of route.patterns) {
      if (pattern.test(stripped)) {
        return { isLong: true, workerType: route.worker };
      }
    }
  }

  // Long task but no specific worker match: use default
  return { isLong: true, workerType: 'default' };
}
